### ISSUE TITLE
Vinculación a LinkedIn

### ISSUE THREAD

**Issue by RosaMariaFdez** [RosaMariaFdez/2022-ISO2-BC2#14]
Cada uno tiene que poner en su nombre en la wiki su enlace a linkedin (si quiere o tiene perfil)

Añadid un comentario indicando cada uno cuando lo hayáis hecho o poniendo que no lo queréis poner, así cierro el issue cuando estemos todos.

**Comment by RosaMariaFdez** [comment]
He añadido mi enlace

**Comment by carsernew** [comment]
He añadido mi enlace

**Comment by Bersaglieri412** [comment]
Faltan únicamente los enlaces de Alejandro y  Mohamed

**Comment by Mohamed11302** [comment]
He añadido mi enlace

**Comment by MedinaMV** [comment]
He añadido mi enlace
