### ISSUE TITLE
Iteración 1 Requisitos

### ISSUE THREAD

**Issue by Bersaglieri412** [RosaMariaFdez/2022-ISO2-BC2#22]

**Comment by RosaMariaFdez** [comment]
Realizados los requisitos y el correspondiente commit.

**Comment by RosaMariaFdez** [comment]
Hemos decidido en la reunión que vamos a ponerlo en visual paradigm en lugar de en word

**Comment by RosaMariaFdez** [comment]
Corregido

**Comment by Mohamed11302** [comment]
Se ha realizado el análisis en una carpeta del Visual que no le correspondía

**Comment by Mohamed11302** [comment]
Corregido
