### ISSUE TITLE
Cambiar la planificación 

### ISSUE THREAD

**Issue by RosaMariaFdez** [RosaMariaFdez/2022-ISO2-BC2#5]
Hay que reestructurar toda la planificación a grupos de dos personas y tomar decisiones para sacar el mayor provecho del tiempo

**Comment by Mohamed11302** [comment]
[Estimaciones y calendario.xlsx](https://github.com/RosaMariaFdez/2022-ISO2-BC2/files/10041808/Estimaciones.y.calendario.xlsx)
[Planificacion.docx](https://github.com/RosaMariaFdez/2022-ISO2-BC2/files/10041809/Planificacion.docx)

**Comment by Bersaglieri412** [comment]
Planificación terminada y subidos archivos correspondientes
